# Site settings
name: 三好五爱
email: maoxiaoke@outlook.com
author: 三好五爱
url: http://xiaokedada.com
resume_site: http://xiaokedada.com/me/
github: https://github.com/maoxiaoke/
baseurl: ""  #根目录
description: ""
motto: 尴尬且不失礼貌的微笑
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner:
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xiaokedada
